package EmotionsLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ActionUnitGroup extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ActionUnitGroup() {
    super(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac917d01cL, "ActionUnitGroup", "r:94d93127-843f-4fa5-aa56-bc1b6a20cd9a(EmotionsLanguage.structure)/4836294162633969692");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_brows_0 = new EnumerationDescriptor.MemberDescriptor("brows", "brows", 0x431df7eac917d01dL, "r:94d93127-843f-4fa5-aa56-bc1b6a20cd9a(EmotionsLanguage.structure)/4836294162633969693");
  private final EnumerationDescriptor.MemberDescriptor myMember_eyes_0 = new EnumerationDescriptor.MemberDescriptor("eyes", "eyes", 0x431df7eac917d01eL, "r:94d93127-843f-4fa5-aa56-bc1b6a20cd9a(EmotionsLanguage.structure)/4836294162633969694");
  private final EnumerationDescriptor.MemberDescriptor myMember_lips_0 = new EnumerationDescriptor.MemberDescriptor("lips", "lips", 0x431df7eac917d021L, "r:94d93127-843f-4fa5-aa56-bc1b6a20cd9a(EmotionsLanguage.structure)/4836294162633969697");
  private final EnumerationDescriptor.MemberDescriptor myMember_other_0 = new EnumerationDescriptor.MemberDescriptor("other", "other", 0x431df7eac917d025L, "r:94d93127-843f-4fa5-aa56-bc1b6a20cd9a(EmotionsLanguage.structure)/4836294162633969701");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac917d01cL, 0x431df7eac917d01dL, 0x431df7eac917d01eL, 0x431df7eac917d021L, 0x431df7eac917d025L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_brows_0, myMember_eyes_0, myMember_lips_0, myMember_other_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_other_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "brows":
        return myMember_brows_0;
      case "eyes":
        return myMember_eyes_0;
      case "lips":
        return myMember_lips_0;
      case "other":
        return myMember_other_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
