package EmotionsLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ActionUnit = 0;
  public static final int ActionUnitList = 1;
  public static final int Emotion = 2;
  public static final int EmotionList = 3;
  public static final int ID = 4;
  public static final int SystemId = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L);
    builder.put(0x431df7eac9136eb2L, ActionUnit);
    builder.put(0x431df7eac9136ebcL, ActionUnitList);
    builder.put(0x431df7eac9136ec3L, Emotion);
    builder.put(0x431df7eac919b6a3L, EmotionList);
    builder.put(0x431df7eac91adf04L, ID);
    builder.put(0x431df7eac9136eafL, SystemId);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
