package EmotionsLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ActionUnit_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new ActionUnitList_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Emotion_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new EmotionList_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new ID_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new SystemId_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136eb2L), MetaIdFactory.conceptId(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136ebcL), MetaIdFactory.conceptId(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136ec3L), MetaIdFactory.conceptId(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac919b6a3L), MetaIdFactory.conceptId(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac91adf04L), MetaIdFactory.conceptId(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136eafL)).seal();
}
