package EmotionsLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class ActionUnit_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("{");
    tgs.newLine();
    tgs.indent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("id");
    tgs.decreaseIndent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append(":");
    tgs.decreaseIndent();
    tgs.append(" ");
    tgs.increaseIndent();
    tgs.indent();
    tgs.append(Integer.toString(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.id$2j0Y)));
    tgs.decreaseIndent();
    tgs.newLine();
    tgs.indent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("name");
    tgs.decreaseIndent();
    tgs.append(" ");
    tgs.increaseIndent();
    tgs.indent();
    tgs.append(":");
    tgs.decreaseIndent();
    tgs.append(" ");
    tgs.increaseIndent();
    tgs.indent();
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.decreaseIndent();
    tgs.newLine();
    tgs.indent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("group");
    tgs.decreaseIndent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append(":");
    tgs.decreaseIndent();
    tgs.append(" ");
    tgs.increaseIndent();
    tgs.indent();
    tgs.append(SEnumOperations.getMemberPresentation(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.group$S3zK)));
    tgs.decreaseIndent();
    tgs.newLine();
    tgs.indent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("endValue");
    tgs.decreaseIndent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append(":");
    tgs.decreaseIndent();
    tgs.append(" ");
    tgs.increaseIndent();
    tgs.indent();
    tgs.append(Integer.toString(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.endValue$2jv0)));
    tgs.decreaseIndent();
    tgs.newLine();
    tgs.indent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("systemIds");
    tgs.decreaseIndent();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append(":");
    tgs.decreaseIndent();
    tgs.newLine();
    tgs.indent();
    for (SNode elem : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.systemIds$2kc3))) {
      tgs.increaseIndent();
      tgs.increaseIndent();
      tgs.indent();
      tgs.appendNode(elem);
      tgs.decreaseIndent();
      tgs.decreaseIndent();
      tgs.newLine();
      tgs.indent();
      if ((SNodeOperations.getNextSibling(elem) != null)) {
        tgs.append(" ");
      }
    }
    tgs.append(" ");
    tgs.append("}");
  }

  private static final class PROPS {
    /*package*/ static final SProperty id$2j0Y = MetaAdapterFactory.getProperty(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136eb2L, 0x431df7eac9136eb5L, "id");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty group$S3zK = MetaAdapterFactory.getProperty(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136eb2L, 0x431df7eac917d02eL, "group");
    /*package*/ static final SProperty endValue$2jv0 = MetaAdapterFactory.getProperty(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136eb2L, 0x431df7eac9136eb7L, "endValue");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink systemIds$2kc3 = MetaAdapterFactory.getContainmentLink(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136eb2L, 0x431df7eac9136ebaL, "systemIds");
  }
}
