package EmotionsLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ID_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(Integer.toString(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.id$S2eW)));
  }

  private static final class PROPS {
    /*package*/ static final SProperty id$S2eW = MetaAdapterFactory.getProperty(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac91adf04L, 0x431df7eac91adf05L, "id");
  }
}
