package EmotionsLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class SystemId_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("id");
    tgs.append(":");
    tgs.append(" ");
    tgs.append(Integer.toString(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.id$2cIW)));
  }

  private static final class PROPS {
    /*package*/ static final SProperty id$2cIW = MetaAdapterFactory.getProperty(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136eafL, 0x431df7eac9136eb0L, "id");
  }
}
