package EmotionsLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import EmotionsLanguage.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.ActionUnit:
        return new ActionUnit_TextGen();
      case LanguageConceptSwitch.ActionUnitList:
        return new ActionUnitList_TextGen();
      case LanguageConceptSwitch.Emotion:
        return new Emotion_TextGen();
      case LanguageConceptSwitch.EmotionList:
        return new EmotionList_TextGen();
      case LanguageConceptSwitch.ID:
        return new ID_TextGen();
      case LanguageConceptSwitch.SystemId:
        return new SystemId_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.ActionUnitList$rE)) {
        String fname = getFileName_ActionUnitList(root);
        String ext = getFileExtension_ActionUnitList(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
      if (root.getConcept().equals(CONCEPTS.EmotionList$T7)) {
        String fname = getFileName_EmotionList(root);
        String ext = getFileExtension_EmotionList(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_ActionUnitList(SNode node) {
    return node.getName();
  }
  private static String getFileName_EmotionList(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_ActionUnitList(SNode node) {
    return "";
  }
  private static String getFileExtension_EmotionList(SNode node) {
    return "";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ActionUnitList$rE = MetaAdapterFactory.getConcept(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac9136ebcL, "EmotionsLanguage.structure.ActionUnitList");
    /*package*/ static final SConcept EmotionList$T7 = MetaAdapterFactory.getConcept(0xcdf28937d3d54028L, 0xbc011c5621e5c4b9L, 0x431df7eac919b6a3L, "EmotionsLanguage.structure.EmotionList");
  }
}
